[project]
name = "mamba-codestral"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "accelerate>=1.7.0",
    "ipykernel>=6.29.5",
    "mlx-lm>=0.25.0",
    "torch>=2.7.1",
    "torchaudio>=2.7.1",
    "torchvision>=0.22.1",
]
