services:
  linux:
    build:
      context: .
    privileged: true
    hostname: linux
    volumes:
      - .:/src
    working_dir: /src

# compose is for simple linux env:
#   docker compose run --rm --build linux
