# syntax=docker/dockerfile:1
FROM ubuntu:latest

RUN apt-get update && apt-get install -y \
    gcc g++ make cmake \
    iputils-ping net-tools iproute2 \
    iperf3 iperf \
    curl wget \
    git fish \
    bat grc