[project]
name = "try-vllm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "torch>=2.7.0.dev20250310",
    "torchaudio>=2.6.0.dev20250311",
    "torchvision>=0.22.0.dev20250311",
]
