[project]
name = "try-vllm"
version = "0.1.0"
dependencies = [
    "graphviz>=0.20.3",
    "ipykernel>=6.29.5",
    "matplotlib>=3.10.1",
    "torchinfo>=1.8.0",
    "torchview>=0.2.6",
    "transformers>=4.49.0",
    "vllm>=0.7.3",
]
