# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "test-ubuntu2410-arm"

  config.vm.box_check_update = false

  config.vm.provider "parallels" do |prl|
    prl.cpus = 10
    prl.memory = 32768
    prl.linked_clone = false # so I can expand drive size manually, else if a linked clone it seems like there is no way to ever expand drive?!

    # TODO: does disk mgmt work with parallels plugin
    # https://github.com/hashicorp/vagrant/pull/11165

    # steps
    # boot VM for first time to create non linked_clone VM
    # vagrant halt => manually expand drive size in parallels GUI
    # vagrant up
    # vagrant ssh
    #
    # lsblk # confirm drive is larger
    # sda                         8:0    0  170G  0 disk
    # ├─sda1                      8:1    0    1G  0 part /boot/efi
    # ├─sda2                      8:2    0    2G  0 part /boot
    # └─sda3                      8:3    0   36G  0 part
    #   └─ubuntu--vg-ubuntu--lv 252:0    0   18G  0 lvm  /
    # sudo lvdisplay
    #   LV Name                ubuntu-lv
    #   LV Size                18.00 GiB
    #
    # 1. resize partition
    # lsblk # confirm
    # sudo parted /dev/sda resizepart 3 100%
    # # Information: You may need to update /etc/fstab. # from resizepart cmd
    # dmsetup info -C   # get current UUID of LV
    # cat /etc/fstab # confirm if UUID in /etc/fstab still matches (it does == good to go)

    # 2. resize PV (b/c using LVM) (= Physical Volume)
    # pvdisplay # confirm
    # sudo pvresize /dev/sda3

    # 3. resize LV (= Logical Volume)
    # lvdisplay # confirm
    # sudo lvextend -l +100%FREE /dev/ubuntu-vg/ubuntu-lv

    # 4. resize filesystem
    # df -h # confirm
    # sudo resize2fs /dev/ubuntu-vg/ubuntu-lv

    # tools
    # sudo apt install -y bat

    # build kernel
    # sudo apt install -y build-essential libncurses-dev bison flex libssl-dev libelf-dev
    # wget https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git/tag/?h=next-20240830
    #       (as of 2024-08-31 => IIUC linux-next is 6.12, cuz 6.11 is in RCs)
    # tar xf linux-next-next-20240830.tar.gz -C ~/
    # make menuconfig
    #   Set DRM_PANIC and DRM_PANIC_DEBUG # try to get these to work (new in 6.10)
    #     *** TODO can I just mod the .config myself to save time and make it reproducible or does it add any depenencies too?
    #     LATER see my notes in linux-next clone for other options to try
    #
    #     FYIk, b/c based on debian config in current VM, need to disable some certs in the .config file:
    #        CONFIG_SYSTEM_TRUSTED_KEYS=""
    #        CONFIG_SYSTEM_REVOCATION_KEYS=""
    #        # untested (look ok)
    #           sed -i 's/^CONFIG_SYSTEM_TRUSTED_KEYS=.*/CONFIG_SYSTEM_TRUSTED_KEYS=""/' .config
    #           sed -i 's/^CONFIG_SYSTEM_REVOCATION_KEYS=.*/CONFIG_SYSTEM_REVOCATION_KEYS=""/' .config
    #
    # make -j$(nproc) # worked!
    #
    # sudo make modules_install
    #
    # sudo make install
    # # FAILS: # ERROR (dkms apport): binary package for parallels-tools: 19.4.0.54962 not found
    #     trying to recompile the kernel module parallel-tools and its not working?
    # dkms status
    #   parallels-tools/19.4.0.54962, 6.8.0-31-generic, aarch64: installed
    # found files:
    #   cat /usr/src/parallels-tools-19.4.0.54962/dkms.conf
    #   ALSO    ls /var/lib/dkms/parallels-tools
    # so is it just not finding the compiled version or? can I skip it?
    # DERP wes the error mentioned:
    #   cat /var/lib/dkms/parallels-tools/19.4.0.54962/build/make.log
    #     ERROR in file during compile... hence why it cannot find the binary!:
    #      /var/lib/dkms/parallels-tools/19.4.0.54962/build/prl_fs/SharedFolders/Guest/Linux/prl_fs/inode.c:874:17: error: implicit declaration of function ‘SetPageError’; did you mean ‘SetPageDirty’? [-Wimplicit-function-declaration]
    #      874 |                 SetPageError(page);
    #   OK IT FAILED TO recompile dkms... can I just skip it?
    #
    # *** try w/o this module, and for now I am removing it from all KERNELS in dkms
    #     sudo dkms remove -m parallels-tools -v 19.4.0.54962 --all
    #     sudo dkms status # confirm nothing now
    #  *** make install # WORKED!
    # ls /boot
    #      vmlinux-6.11.0-rc5-next-20240830    # ok so its marked rc5-next ==? 6.12
    #         it has the flags I want for DRM_PANIC so i'm fine with it so far, must be 6.12 and not marked that way yet? not gonna be a 6.11 rc6 prep right? I don't think that has its own git tree?!
    #
    # upon inspection grub has new menuentry for kernel
    #   sudo cat /boot/grub/grub.cfg
    # SO, set grub to wait 10 seconds so I can select it one off:
    #   sudo sed -i 's/^GRUB_TIMEOUT=.*/GRUB_TIMEOUT=10/' /etc/default/grub
    #   sudo update-grub
    # OPEN PARALLELS GUI to current machine
    #   sudo reboot # OR better yet send reboot from parallels GUI and make sure the window (GUI) is focused so keys work
    #   once it reboots, hit ESC (one time) and grub will show shortly after, pick new kernel... if it works can update grub to use it by default!!!
    #
    # uname -a # verify kernel :)

  end

end
